### ISSUE TITLE
Google Pay disappears when switching betwen plans

### ISSUE THREAD

**Issue by sweetcv** [mixaDev/checkout-vue#12]
Hi guys, we have a problem. Our app uses embedded payment page with Fondy's checkout-vue. When our users navigate from one plan to another GooglePay button suddenly disappears. It starts showing again only after full page reload or when changing page size 🤔 PS. Seems like it happens only when `full_screen: true`

https://user-images.githubusercontent.com/61332100/135534898-36606652-d40a-42b7-9ae9-de8d6b1dcdd9.mp4

You can reproduce it on our service at https://sweetcv.com Just sign up, click Upgrade and choose the plan to get to the payment page shown on video.

We could also reproduse quite the same problem on your payment portal. See the following video:

https://user-images.githubusercontent.com/61332100/135534053-c7ef3475-cabc-4b06-8057-61eb9322765c.mp4

Please, help us fixing this ASAP. Thanks!

**Comment by mixaDev** [comment]
Thank you!
