### ISSUE TITLE
TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by sweetcv** [mixaDev/checkout-vue#8]
Hi guys,

We've been using Fondy (embedded via checkout-vue) in production starting from 07.03.2021 and everything worked fine until 03.04.2021 when we started receiving weird errors throwed on client-side for our customers. Here's how these erros look like:

![image](https://user-images.githubusercontent.com/61332100/114108811-9a118a80-98dc-11eb-995e-2f3cd5b83c70.png)

Our use case is pretty straightforward: we have an Angular SPA and we need that `checkout-vue/checkout.js` was loaded asynchronusly once user navigates to the payment page. So we dynamically initiate loading the required script, wait until it gets loaded and only then initiate creating the payment form. Here's a brief example of the function that we use to load `checkout.js` file:

![image](https://user-images.githubusercontent.com/61332100/114112963-37bd8780-98e6-11eb-9f1d-cd0c1b040fe0.png)

Basically it worked just filne and we didn't do any changes on our side, so we suspect there was some update recently on Fondy's side, so we started digging into it. And it seems like the problem is happening because of the asynchronus load. For example, if we disable our `loadScript` functionality and just add these lines into `index.html`:

![image](https://user-images.githubusercontent.com/61332100/114111810-8ddcfb80-98e3-11eb-81d9-96d728200398.png)

The result will be the same - the error once we init the form. 

![image](https://user-images.githubusercontent.com/61332100/114114652-efa06400-98e9-11eb-8600-da1107debee7.png)

BUT if we remove `async` parameter everything works just fine. Maybe you have any ideas on how we can eliminate this problem?

UPD: it turns out that problem disappears if we cleanup all the cookies & remove these elements from payment methods 🤔

![image](https://user-images.githubusercontent.com/61332100/114115585-c385e280-98eb-11eb-9d80-a37fac161c4d.png)

Thanks

**Comment by mixaDev** [comment]
This is the Google / Apple Pay button insert.
At the time of the insert there is no DOM element.
Caused by the fact that `options.methods` differ from `server.methods`.
This is not a critical error.
In the near future it will be corrected.

**Comment by sweetcv** [comment]
Hi @mixaDev, thanks for clarifying. How do we understand what is the `server.methods` in our case to make it identical?
